### ISSUE TITLE
Migrate Zeek-on-Windows into Brim's GitHub org

### ISSUE THREAD

**Issue by philrz** [brimsec/zeek#13]
The scripts in https://github.com/brimsec/zeek/tree/master/brim/windows all still point to branches in @henridf's personal GitHub and other select gists/URLs. While we much appreciate @henridf's contribution in getting Brim to the current level of Windows support [ 😄 ] , to ensure cleanliness and stability we should migrate the referenced branches/code to be under Brim's GitHub org.

**Comment by henridf** [comment]
As part of this we should also contribute upstream those changes which we think are likely of interest to their upstreams.
