### ISSUE TITLE
fail to ingest pcap: ensureSpawnedProcessTermination failed: Access is denied.

### ISSUE THREAD

**Issue by alfred-landrum** [brimsec/zeek#16]
From [a user report in our public Slack](https://brimsec.slack.com/archives/C010DR0HHMF/p1587085836076400) forum: When they tried to ingest a pcap, they saw this error message `ensureSpawnedProcessTermination failed: Access is denied.`  That's from our zeek-launcher that was added in https://github.com/brimsec/zeek/pull/9 . We've asked for a `systeminfo` dump to see their Windows version.

**Comment by alfred-landrum** [comment]
The user reported they hit this on Windows 7 (`6.1.7601 Service Pack 1 Build 7601`). We're not testing on Windows 7, but our Electron & Go versions do support it.

**Comment by alfred-landrum** [comment]
I'm closing this for now, as the user reported that an upgrade to Brim v0.8.0 resolved the issue. However, we don't think we made any relevant changes to the related code.

We also don't have a version of Windows 7 available that we can try this ourselves - it's out of support from Microsoft. We'll re-open if we get other reports.

**Comment by philrz** [comment]
While we don't know with certainty precisely what addressed the issue, the user did circle back with an additional comment we can keep in mind should this symptom surface again:
> I Just restart my computer.Likely I run brim in administrator privileges.
