### ISSUE TITLE
Support adding plugin Zeek Packages in our build system

### ISSUE THREAD

**Issue by philrz** [brimsec/zeek#37]
In a normal Zeek environment, adding Community ID support has the potential to be simple, since one could use the Zeek Package Manager to install the package https://github.com/corelight/zeek-community-id. However, in the Zeek artifact that's bundled with Brim, there's a couple challenges due to the fact that this package is a _plugin_  that includes C++ code, rather than just a collection of Zeek scripts.

Known challenges include:

1. We've been minimizing the size of the artifact, such that some pieces needed to compile such code are not currently present. The `zeek-config` script and headers are two things we're aware of offhand that we think will be needed, but there may be others.

2. @nwt has confirmed that `zeek-config` didn't work when he was last working on our Windows build process, and that there's additional complications to this because the plugin framework simply doesn’t work on Windows yet.

Therefore the high-level goal is to enhance our fork of Zeek and our build system (both in general and for Windows in particular) such that a plugin like the Community ID one can be added like we currently do for other script-based Zeek Packages.

**Comment by nwt** [comment]
Done in #43.
