### ISSUE TITLE
Add Zeek Package for Community ID to release artifact

### ISSUE THREAD

**Issue by philrz** [brimsec/zeek#38]
Assuming a seamless implementation of https://github.com/brimsec/zeek/issues/37, adding https://github.com/corelight/zeek-community-id to our Zeek artifacts should be a trivial change to [this section of the `release` script](https://github.com/brimsec/zeek/blob/83df0493ce0f44d67edf93d5911941778f84db55/brim/release#L58-L70) similar to how we install other Zeek Packages.

**Comment by nwt** [comment]
Done in #43.
